# Generated by Django 3.1.4 on 2020-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasket', '0005_auto_20201209_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='completed_tasks',
            field=models.ManyToManyField(related_name='completedtask', to='tasket.Task'),
        ),
    ]
